language: go
sudo: false
matrix:
  include:
    - go: 1.x

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get
  - go get golang.org/x/sys/windows || true
  - gox

deploy:
  provider: releases
  api_key:
    secure: fixme
  file_glob: true
  file: dkz_*
  skip_cleanup: true
  on:
    repo: glehmann/dkz
    tags: true
