language: go
sudo: false
matrix:
  include:
    - go: 1.x

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get
  - gox -os linux

deploy:
  provider: releases
  api_key:
    secure: QhT7qj37HyrSmnNN4VmMBDtBNdgivOmTNwzgyRO/Tm90BlZVYvBUUVBFsa33BPCg9VnWFXnpWubqIq2Cpn6Q8dUqlqBA3VZwAHLlNCKzzvr7s0LxRM5fYpuUGoYd1P33dIN2VQmB83Jiyqk4JQTUbgCIGrVBKw2VB4QRy6uVtVqB8WCJD7FRMRn/HGiSBR2AQjwq43R6H94CJvxEKCXJ7SVq5tXjVnap4KTuH52Jg0Qr21T+X4ZEYTSJSE16qwkhGBYyakM6aDdOMmf9xZ+/AXIhaIUlO27E1YxOVfqVAvTTnzZSSfP4bR9CUY/jRQ7/4J433tezcyUMOGyls2+eIiIRM/QZws0XlroIP0ALkmzxOWQBLbHAM86lkdUAXGpGckathvYWvcikm/GmDBpsXPPuBfJXOVAPxRRlaRXLlsFv4WuUYGz5u0nAK39+VDFKm/ApAHjPovkEOGFrGKRTHRSe3miNpghasEBWCmI8/mRptG9tyO5wq67iVIOx6iBh1OjDw3pRkYw6RE/RaA00GtIUGhjCeKx6NctUczqdzfwehfdpuB7QDhf/MrLa5XX6zvENlm5HxkP+/2WaSM9AGiiM2aHHr16jSiDfftdBQ15uLxIjVYSi+hlJDYlWLlNGfWKd5sV0aM5IuvZw/TQJZo20woLKoicAEjGiSkmuG38=
  file_glob: true
  file: dkz_*
  skip_cleanup: true
  on:
    repo: glehmann/dkz
    tags: true
